# Numpy
- 빠르고 효율적인 수치 계산을 위한 라이브러리
- 다차원 배열 지원 -> 대용량 데이터를 빠르게 처리 가능
- 포괄적인 수학 함수, 고급 수학 구현 가능
- ndarray (array) 지원
   - 동일한 데이터 타입으로 구성, index 값을 가짐 

In [2]:
#넘파이를 가져와서 np라는 약어로 사용 
import numpy as np

In [4]:
# ndarray 생성
arr = np.array ([1, 2, 3, 4 ,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
list2 = [[1,2,3],[4,5,6]]
#리스트 안에 리스트가 들어간 2차원의 구조를 가지고 있음. 
arr2 = np.array(list2)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# ndarray 확인 #크기를 확인하려면 shape 활용
arr2.shape

(2, 3)

In [9]:
# ndarray 확인 
print ( arr2.shape )
print ( arr2.size ) #배열 내부 요소 개수 즉 숫자가 6개 들어있다. 
print ( arr2.ndim ) #배열의 차원 확인 
print ( arr2.dtype ) #배열 내부 요소의 데이터 타입 확인

(2, 3)
6
2
int64


In [10]:
#배열은 index를 가짐 -> 인덱싱, 슬라이싱 
#인덱싱 : 가르키다, 인덱스 번호 자리 가르킴  -> 데이터 한개 추출 / 배열명 [ index값 ]
#슬라이싱 : 잘라오다, 시작~끝 범위를 잘라옴 -> 여러개의 데이터 추출 / 배열명 [ 시작 : ]

In [11]:
# np.arange(): 숫자 범위 배열 생성
 #np. arange(시작, 끝(포함x), 증감)
np.arange( 1,5 )

array([1, 2, 3, 4])

In [14]:
#0~49 숫자 배열 만들기 
arr = np.arange(50)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [18]:
# 배열의 크기 재지정: reshape() #갯수는 같아야 함 
# 원래 배열의 요소 개수, 바뀔 배열의 요소 개수가 같아야 함 
arr2 = arr.reshape( 5, 10) #5행 10열로 바꾸겠
arr2 #변수에 담은 것 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [21]:
arr2 [ 0 ]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr2 [ : , 0]

array([ 0, 10, 20, 30, 40])

In [23]:
arr2 [ 3, 1:5]

array([31, 32, 33, 34])

In [24]:
arr2 [ 3, 6:10]

array([36, 37, 38, 39])

In [29]:
arr2 [2:4,2:5]

array([[22, 23, 24],
       [32, 33, 34]])

### BMI 값 구하기 
- txt 파일 불러오는 방법 알기
- numpy 배열 연산 진행하기
- 1m = 100cm /(cm단위 /100 -> m)
- 1kg = 2.204pound (pound / 2.204 -> kg)

In [42]:
# txt를 불러오는 함수 : Loadtxt()
# 외부 파일을 불러올 때는 "경로/파일명.확장자" 정확하게 기록
data = np.loadtxt('data/height_weight(p).txt', delimiter = ",")
data
#delimite: 구분 기호 

array([[175.2   , 180.3   , 175.    , 169.2   , 185.2   , 188.    ,
        177.6   , 178.2   , 177.    , 179.    ],
       [144.5824, 193.952 , 174.5568, 152.7372, 121.22  , 156.9248,
        160.892 , 151.8556, 163.096 , 180.728 ]])

In [55]:
#bmi지수 구하기 
height_cm = data[0]
weight_p = data[1]

#데이터를 키와 몸무게 정보로 나누기 

#1cm = 0.01m ->키를 m 단위로 바꾸기
height_m = height_cm / 100
#2.204kg = 1pound -> 몸무게를 kg 단위로 바꾸기
weight_kg = weight_p / 2.204
#BMI지수 구하기 
BMI = weight_kg/ height_m*height_m
BMI

array([65.6, 88. , 79.2, 69.3, 55. , 71.2, 73. , 68.9, 74. , 82. ])

In [56]:
BMI

array([65.6, 88. , 79.2, 69.3, 55. , 71.2, 73. , 68.9, 74. , 82. ])

### 특정한 값으로 배열 생성하기

In [3]:
import numpy as np
# 모든 요소가 0으로 이루어진 배열 생성 
arr_zeros = np.zeros( (2, 3) )
arr_zeros.dtype #float 데이터 타입으로 생성됨

dtype('float64')

In [4]:
np.zeros( (2, 3,), dtype = int )

array([[0, 0, 0],
       [0, 0, 0]])

In [5]:
#모든 요소가 1으로 이루어진 배열 생성
np.ones( (3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [6]:
# 내가 원하는 값으로 채워진 배열 생성
np.full((2,7),3) #크기가 필요함  

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

In [7]:
#내가 원하는 특정 위치에 값을 채워넣기 
#np.arange(시작(0), 끝(반드시 지정), 증감(1))

In [9]:
#랜덤값으로 채워진 배열 생성 
np.random.randint( 0, 2, (3,4))#배열의 크기 

array([[1, 0, 0, 1],
       [0, 1, 0, 0],
       [1, 0, 1, 1]], dtype=int32)

### Boolean 인덱싱 
- 조건에 해당하는 데이터만 출력할 때 사용
- True에 해당하는 (즉, 조건에 맞는) 값들만 추출 

In [10]:
#점수 배열 생성
score = np.array ( [80, 70 ,55, 97, 54] )
score

array([80, 70, 55, 97, 54])

In [11]:
score >= 60
# 불리언 (T/F)

array([ True,  True, False,  True, False])

In [12]:
score [ 2:4]

array([55, 97])

In [14]:
#변수[ 조건(T/F) ]
score [ score >= 60]

array([80, 70, 97])

In [15]:
name = np.array(['김지나', '정준석', '곽은비', '서채은', '산현서'])
name

array(['김지나', '정준석', '곽은비', '서채은', '산현서'], dtype='<U3')

In [18]:
#'서채은' 만 출력
name == '서채은'

array([False, False, False,  True, False])

In [19]:
name [name == '서채은']

array(['서채은'], dtype='<U3')

In [23]:
name_score = np.array([['지원',100],
                       ['민철',90],
                       ['기준',80],
                       ['지희',70]])

name_score


array([['지원', '100'],
       ['민철', '90'],
       ['기준', '80'],
       ['지희', '70']], dtype='<U21')

In [32]:
#민철의 정보를 가져오기 -> =='민철'
#1)  이름 정보만 가져오기 
name_score [ : ,0]

array(['지원', '민철', '기준', '지희'], dtype='<U21')

In [39]:
#2) 1에서 가져온 이름 정보 값이 '민철'인지 아닌지 판멸
name_score[ :, 0] == '민철'


array([False,  True, False, False])

In [40]:
#3) '민철'의 정보를 가져오기 => 불리언 인덱싱 
name_score[name_score[ :, 0] == '민철']

array([['민철', '90']], dtype='<U21')

In [43]:
#점수가 80점 이하인 정보
#1) 점수 정보만 가져오기 
name_score [ :,1]

#문자를 숫자로 먼저 바꿔줘야 함. 

#3) 점수가 80점 이하 조건 => 불리언 인덱싱 

array(['100', '90', '80', '70'], dtype='<U21')

In [56]:
#문자를 숫자로 먼저 바꿔줘야 함. 
name_score [ :,1].astype('int') <= 80
#2) 1에서 가져온 점수 정보 값이 80 이하인지 판별


array([False, False,  True,  True])

In [57]:
#3) 점수가 80점 이하 조건 => 불리언 인덱싱 
name_score[name_score [ :,1].astype('int') <= 80]

array([['기준', '80'],
       ['지희', '70']], dtype='<U21')

### Numpy 배열에서의 논리연산 (and, or, not)
- ndarray의 조건연산은 '기호'를 사용
- and :&, or:|, not:~
- 소괄호()를 이용해 조건의 우선순위 지정 

### 영화 평점 구하기

In [64]:
#데이터 로드
#np.loadtxt 다중문자 지원 X
#np.genfromtxt 다중문자 지원
data = np.genfromtxt('data/ratings.txt', delimiter = '::', dtype = None )
data

#사용자 ID, 영화ID, 평점, 영화 시

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]])

In [65]:
data.shape

(1000209, 4)

In [66]:
data.ndim

2

In [67]:
data.size

4000836

### 각 사용자 별 평점 구하기
1) 전체 영화 평점 평균 구하기


In [69]:
#1) 평점 정보만 가져오기
data[ : , 2]
#2) 평점 정보의 평균 구하기 -> mean()
data[ : , 2].mean()

np.float64(3.581564453029317)

In [71]:
# 전체 평점의 합계 구하기 
data[ : , 2].sum ()

np.int64(3582313)

- 사용자별 영화 펴점 구하기
  - 1번 사용자 ID의 평점 평균 구하기
    

In [82]:
#1) 1번 사용자 ID 정보만 가져오기 
#1-1. 전체 정보(data)에서 ID정보만 가져오기 
data [ : , 0]

#1-2. ID 1안지 판별 -> 불리언 결과 값
data [ : , 0] == 1

#1-3. 1번 사용자 정보만 출력 -> 불리언 
user1 = data[data [ : , 0] == 1]

#2) 1번 ID 정보에서 평점 평균 구하기 
user1[ : , 2].mean()

print(f"1번 사용자의 평점은 {user_1[ : , 2].mean()} 입니다.")

1번 사용자의 평점은 4.188679245283019 입니다.


In [86]:
#3 번 사용자의 평점 평균 가지고 오기 

user3 = data[data [ : , 0] == 3]

user3[ : , 2].mean()

np.float64(3.9019607843137254)

In [90]:
#전체 사용자 확인
#중복없는 ID의 유일 값 확인 
user_id = np.unique(data[ : , 0])
user_id
#각각의 사용자가 몇 편의 영화를 봤는지 
len(user_id)

6040

### 각 사용자 별 평점 평균

In [114]:

user_ratings=[]
# -> n번 사용자의 평점 평균 구하기 
# -> 같은 코드의 반복?
for u in user_id:
    user_data = data[ data[ : , 0] == u ] #id별정보(사용자, 영화, 평점, 시간)
    user_mean = user_data[ : , 2].mean()
    user_ratings.append([int(u), float(user_mean)])
    #round(소수 데이터, 소숫점 뒤 숫자개수)
    #print(user_mean)

user_ratings    98


#2. 결과 화면을 보면, [] <- 이중 리스트에 모든 정보가 담겨 있음
# -> 리스트에 정보를 담아야함 (추가해야함)

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.884892086330935],
 [9, 3.7358490566037736],
 [10, 4.114713216957606],
 [11, 3.2773722627737225],
 [12, 3.8260869565217392],
 [13, 3.388888888888889],
 [14, 3.32],
 [15, 3.3233830845771144],
 [16, 3.0285714285714285],
 [17, 4.075829383886256],
 [18, 3.6491803278688524],
 [19, 3.5725490196078433],
 [20, 4.083333333333333],
 [21, 2.909090909090909],
 [22, 3.0673400673400675],
 [23, 3.3157894736842106],
 [24, 3.948529411764706],
 [25, 3.7411764705882353],
 [26, 2.96],
 [27, 4.171428571428572],
 [28, 3.7570093457943927],
 [29, 3.5833333333333335],
 [30, 3.488372093023256],
 [31, 3.73109243697479],
 [32, 3.625],
 [33, 3.498721227621483],
 [34, 3.8658536585365852],
 [35, 3.54040404040404],
 [36, 4.199430199430199],
 [37, 3.69811320754717],
 [38, 3.58],
 [39, 3.564516129032258],
 [40, 3.4479166666666665],
 [41, 

- 평점 평균이 4 이상인 사용자 

In [116]:
#리스트 -> 불리언 인덱싱 등 x
#numpy 의 배열로 형 변환 
user_rating_arr = np.array(user_ratings)
user_rating_arr

array([[1.00000000e+00, 4.18867925e+00],
       [2.00000000e+00, 3.71317829e+00],
       [3.00000000e+00, 3.90196078e+00],
       ...,
       [6.03800000e+03, 3.80000000e+00],
       [6.03900000e+03, 3.87804878e+00],
       [6.04000000e+03, 3.57771261e+00]])

In [117]:
#평점 평균이 4 이상인지 판별
user_rating_arr [ :,1] >=4

array([ True, False, False, ..., False, False, False])

In [118]:
#평점 평균이 4 이상인 정보(데이터)
user_rating_arr[user_rating_arr [ :,1] >=4]

array([[1.00000000e+00, 4.18867925e+00],
       [4.00000000e+00, 4.19047619e+00],
       [7.00000000e+00, 4.32258065e+00],
       ...,
       [6.02700000e+03, 4.25000000e+00],
       [6.03200000e+03, 4.13461538e+00],
       [6.03400000e+03, 4.09523810e+00]])

In [119]:
#평점 평균이 4 이상인 사용자 정보만 가져오기 
user_rating_arr[user_rating_arr [ :,1] >=4][ :,0]

array([1.000e+00, 4.000e+00, 7.000e+00, ..., 6.027e+03, 6.032e+03,
       6.034e+03])

In [120]:
user_rating_arr[user_rating_arr [ :,1] >=4][ :,0].astype(int)

array([   1,    4,    7, ..., 6027, 6032, 6034])

In [122]:
user_ratings #이 정보를 외부에 저장 시키기. 

np.savetxt('data/rating_mean.csv', user_ratings, delimiter = ',', fmt ='%3.f')